//! The oracle net for tool input schemas.
//!
//! `cc_input_schemas.json` is generated by running the real CC tool modules
//! under `bun` and projecting each `tool.inputSchema` through zod v4's
//! `toJSONSchema` — the same call `utils/zodToJsonSchema.ts` wraps and
//! `utils/api.ts:160` ships to the API as `input_schema`. Regenerate with:
//!
//! ```text
//! cd ../rebuild && bun ../CometixCode/scripts/dump_cc_tool_schemas.mjs \
//!   > ../CometixCode/src/tools/cc_input_schemas.json
//! ```
//!
//! A tool listed in [`MIGRATED`] has had its hand-written JSON literal replaced
//! by the carrier projection, and must reproduce CC's output exactly. Tools not
//! yet listed still carry a literal; adding one here is what "migrated" means.
//!
//! [`OUTSIDE_THE_NET`] records the oracle entries no `fn() -> Tool` can serve,
//! and [`no_oracle_entry_is_silently_dropped`] keeps the two lists exhaustive so
//! a tool cannot fall out of the net unnoticed.

use crate::utils::test_env::{EnvVarGuard, TEST_ENV_LOCK, TestEnvGuard};
use serde_json::Value;

const ORACLE: &str = include_str!("cc_input_schemas.json");

/// Oracle key → the Rust constructor whose `input_schema` must match it. The key
/// is the CC tool directory, or `Dir::ExportName` where one directory ships
/// several tools.
type SchemaFn = fn() -> crate::types::tools::Tool;
const MIGRATED: &[(&str, SchemaFn)] = &[
    ("AgentTool", crate::tools::agent_tool::agent_tool_schema),
    (
        "AskUserQuestionTool",
        crate::tools::ask_user_question_tool::ask_user_question_tool_schema,
    ),
    ("BashTool", crate::tools::bash_tool::bash_tool_schema),
    ("BriefTool", crate::tools::brief_tool::brief_tool_schema),
    ("ConfigTool", crate::tools::config_tool::config_tool_schema),
    (
        "EnterPlanModeTool",
        crate::tools::enter_plan_mode_tool::enter_plan_mode_tool_schema,
    ),
    (
        "EnterWorktreeTool",
        crate::tools::enter_worktree_tool::enter_worktree_tool_schema,
    ),
    (
        "ExitPlanModeTool",
        crate::tools::exit_plan_mode_tool::exit_plan_mode_tool_schema,
    ),
    (
        "ExitWorktreeTool",
        crate::tools::exit_worktree_tool::exit_worktree_tool_schema,
    ),
    (
        "FileEditTool",
        crate::tools::file_edit_tool::file_edit_tool_schema,
    ),
    (
        "FileReadTool",
        crate::tools::file_read_tool::file_read_tool_schema,
    ),
    (
        "FileWriteTool",
        crate::tools::file_write_tool::file_write_tool_schema,
    ),
    ("GlobTool", crate::tools::glob_tool::glob_tool_schema),
    ("GrepTool", crate::tools::grep_tool::grep_tool_schema),
    ("LSPTool", crate::tools::lsp_tool::lsp_tool_schema),
    (
        "ListMcpResourcesTool",
        crate::tools::list_mcp_resources_tool::list_mcp_resources_tool_schema,
    ),
    ("MCPTool", crate::tools::mcp_tool::mcp_tool_schema),
    (
        "NotebookEditTool",
        crate::tools::notebook_edit_tool::notebook_edit_tool_schema,
    ),
    (
        "PowerShellTool",
        crate::tools::powershell_tool::powershell_tool_schema,
    ),
    (
        "ReadMcpResourceTool",
        crate::tools::read_mcp_resource_tool::read_mcp_resource_tool_schema,
    ),
    (
        "RemoteTriggerTool",
        crate::tools::remote_trigger_tool::remote_trigger_tool_schema,
    ),
    (
        "ScheduleCronTool::CronCreateTool",
        crate::tools::schedule_cron_tool::cron_create_tool_schema,
    ),
    (
        "ScheduleCronTool::CronDeleteTool",
        crate::tools::schedule_cron_tool::cron_delete_tool_schema,
    ),
    (
        "ScheduleCronTool::CronListTool",
        crate::tools::schedule_cron_tool::cron_list_tool_schema,
    ),
    (
        "SendMessageTool",
        crate::tools::send_message_tool::send_message_tool_schema,
    ),
    ("SkillTool", crate::tools::skill_tool::skill_tool_schema),
    (
        "TaskCreateTool",
        crate::tools::task_create_tool::task_create_tool_schema,
    ),
    (
        "TaskGetTool",
        crate::tools::task_get_tool::task_get_tool_schema,
    ),
    (
        "TaskListTool",
        crate::tools::task_list_tool::task_list_tool_schema,
    ),
    (
        "TaskOutputTool",
        crate::tools::task_output_tool::task_output_tool_schema,
    ),
    (
        "TaskStopTool",
        crate::tools::task_stop_tool::task_stop_tool_schema,
    ),
    (
        "TaskUpdateTool",
        crate::tools::task_update_tool::task_update_tool_schema,
    ),
    (
        "TeamCreateTool",
        crate::tools::team_create_tool::team_create_tool_schema,
    ),
    (
        "TeamDeleteTool",
        crate::tools::team_delete_tool::team_delete_tool_schema,
    ),
    (
        "TodoWriteTool",
        crate::tools::todo_write_tool::todo_write_tool_schema,
    ),
    (
        "ToolSearchTool",
        crate::tools::tool_search_tool::tool_search_tool_schema,
    ),
    (
        "WebFetchTool",
        crate::tools::web_fetch_tool::web_fetch_tool_schema,
    ),
    (
        "WebSearchTool",
        crate::tools::web_search_tool::web_search_tool_schema,
    ),
];

/// Oracle entries with no constructor the net can call, and why.
const OUTSIDE_THE_NET: &[(&str, &str)] = &[
    (
        "SyntheticOutputTool",
        "CC `createSyntheticOutputTool(jsonSchema)` returns the caller's schema \
         verbatim (`SyntheticOutputTool.ts:31`); the oracle only froze the empty \
         placeholder the dump script passed in, so there is nothing of Cometix's \
         own to compare.",
    ),
    (
        "testing",
        "CC `tools/testing/TestingPermissionTool.tsx:31` hardcodes \
         `isEnabled()` to a comparison that is false in production builds, so \
         the tool exists only for CC's own end-to-end tests. Cometix does not \
         port it (`docs/TOOLS_GAP_INVENTORY.md`), so there is no constructor to \
         compare.",
    ),
];

/// What production CC projects at a patched pointer. A gate does not only
/// change a value: CC builds gated schemas with `.omit({ key: true })`
/// (`AgentTool.tsx:242`, `:252-254`), which takes the property OUT, and no
/// replacement value can express that.
enum ProductionProjection {
    /// Production carries this node where the dump carried another.
    Node(Value),
    /// Production has no such property at all.
    Omitted,
}

/// Pointers where the oracle is the ALL-FEATURES-OFF projection and production
/// CC is not, carrying what the harness could not produce.
///
/// `dump_cc_tool_schemas.mjs` imports the CC modules under plain `bun`, where
/// `bun:bundle`'s `feature()` is FALSE for every flag. Measured in `../rebuild`
/// (the call must sit in an `if`/ternary or bun refuses to evaluate it):
///
/// ```text
/// $ bun -e "import {feature} from 'bun:bundle';
///           console.log(feature('TRANSCRIPT_CLASSIFIER') ? 'ON' : 'OFF')"
/// OFF                                  # same for KAIROS and BASH_CLASSIFIER
/// ```
///
/// Production CC takes those flags from `scripts/build.ts`, which is also the
/// source `utils/feature_flags.rs` follows (see its `BASH_CLASSIFIER` and
/// `AGENT_MEMORY_SNAPSHOT` notes). An entry lands here only when the oracle and
/// the port disagree for THAT reason, and the oracle is PATCHED with the
/// production projection rather than the key being skipped — the pointer stays
/// under the net, and the patch reads that projection off the schema owner so
/// it tracks the gate instead of hardcoding one side of it.
///
/// `(tool, pointer, projection, reason)`, where the projection also receives
/// the DUMPED node so an entry whose gate is currently off can hand it straight
/// back — the same reason the [`ProductionProjection::Node`] entries read a
/// schema owner rather than a literal.
type OraclePatch = (
    &'static str,
    &'static str,
    fn(&Value) -> ProductionProjection,
    &'static str,
);
const GATE_DEPENDENT_ORACLE_PATCHES: &[OraclePatch] = &[
    (
        "AgentTool",
        "/properties/mode/enum",
        |_dumped| {
            ProductionProjection::Node(
                crate::utils::zod_to_json_schema::zod_to_json_schema(
                    crate::utils::permissions::permission_mode::permission_mode_schema(),
                )["enum"]
                    .clone(),
            )
        },
        "CC `AgentTool.tsx:205` declares `mode` with `permissionModeSchema()` — \
         `z.enum(PERMISSION_MODES)`, the INTERNAL set — and `types/permissions.ts:33-38` \
         appends `auto` to it under `feature('TRANSCRIPT_CLASSIFIER')`, which \
         `scripts/build.ts:76` lists as true. CC exports `externalPermissionModeSchema` \
         one line below (`permissionMode.ts:22-24`) and AgentTool does not use it; \
         `PermissionUpdateSchema.ts:64` is its only user.",
    ),
    (
        "AgentTool",
        "/properties/run_in_background",
        |dumped| {
            if crate::tools::agent_tool::omits_run_in_background() {
                ProductionProjection::Omitted
            } else {
                ProductionProjection::Node(dumped.clone())
            }
        },
        "CC `AgentTool.tsx:252-254` returns `schema.omit({ run_in_background: true })` \
         when `isBackgroundTasksDisabled || isForkSubagentEnabled()`, and \
         `scripts/build.ts:45` ships `FORK_SUBAGENT: true`, so production drops the \
         property — forking routes every spawn through `forceAsync` (`:812`) and the \
         parameter would be a no-op. Under `bun` the dump saw `feature('FORK_SUBAGENT')` \
         false and kept it. The condition is read back off \
         `agent_tool::omits_run_in_background`, the same predicate the schema builder \
         uses, so this entry tracks both halves of that `||` instead of asserting one.",
    ),
];

/// Ported tools the oracle never captured, so their schemas stay unverified.
/// Empty: the dump script keys every tool a directory exports, not just the one
/// in `<Dir>/<Dir>.ts`, so `ExitPlanModeTool` (ships from `ExitPlanModeV2Tool.ts`)
/// and `ScheduleCronTool` (three tools, no same-named entry file) are in the
/// oracle. A tool lands here only if CC stops exporting a projectable schema for
/// it.
const AWAITING_AN_ORACLE_ENTRY: &[(&str, &[&str])] = &[];

/// The environment `dump_cc_tool_schemas.mjs` ran under, restored for as long
/// as a comparison is in flight.
///
/// Three migrated constructors read the process environment when they are
/// *called*, where CC reads it once at module load: a truthy
/// `CLAUDE_CODE_DISABLE_BACKGROUND_TASKS` drops `run_in_background` from
/// `BashTool`, `PowerShellTool` and `AgentTool`, and `BASH_MAX_TIMEOUT_MS` /
/// `BASH_DEFAULT_TIMEOUT_MS` rewrite the `timeout` description of the first
/// two. `TEST_ENV_LOCK` alone only serialises against a test mutating them
/// alongside this one; it cannot undo a value a test leaked before this one
/// was scheduled, and that leak would read here as a parity failure against
/// whichever tool lost a property.
///
/// Fields drop in declaration order, so the variables go back before the lock
/// is released.
struct OracleEnvironment {
    _variables: [EnvVarGuard; 3],
    _lock: TestEnvGuard<'static>,
}

impl OracleEnvironment {
    fn pin() -> Self {
        let lock = TEST_ENV_LOCK
            .lock()
            .unwrap_or_else(std::sync::PoisonError::into_inner);
        Self {
            _variables: [
                EnvVarGuard::unset("CLAUDE_CODE_DISABLE_BACKGROUND_TASKS"),
                EnvVarGuard::unset("BASH_MAX_TIMEOUT_MS"),
                EnvVarGuard::unset("BASH_DEFAULT_TIMEOUT_MS"),
            ],
            _lock: lock,
        }
    }
}

fn oracle() -> Value {
    serde_json::from_str(ORACLE).expect("oracle parses")
}

fn oracle_schema(tool_dir: &str) -> Value {
    let mut schema = oracle()
        .get(tool_dir)
        .unwrap_or_else(|| panic!("no oracle entry for {tool_dir}"))
        .get("schema")
        .expect("oracle entry has a schema")
        .clone();
    for (patched_tool, pointer, projection, _) in GATE_DEPENDENT_ORACLE_PATCHES {
        if *patched_tool != tool_dir {
            continue;
        }
        let dumped = schema.pointer(pointer).unwrap_or_else(|| {
            panic!("{tool_dir} oracle has no {pointer} to patch — the harness moved")
        });
        match projection(dumped) {
            ProductionProjection::Node(node) => {
                *schema
                    .pointer_mut(pointer)
                    .expect("the pointer resolved a line above") = node;
            }
            ProductionProjection::Omitted => remove_at_pointer(&mut schema, pointer),
        }
    }
    schema
}

/// Delete the member a JSON pointer names, so a `.omit()`ed property leaves the
/// oracle the way it left CC's schema. `serde_json` has `pointer_mut` but no
/// removal, so the pointer is split into its parent and the final token.
fn remove_at_pointer(schema: &mut Value, pointer: &str) {
    let (parent_pointer, key) = pointer
        .rsplit_once('/')
        .unwrap_or_else(|| panic!("{pointer} is not a JSON pointer"));
    let key = key.replace("~1", "/").replace("~0", "~");
    let parent = schema
        .pointer_mut(parent_pointer)
        .unwrap_or_else(|| panic!("{pointer} has no parent to remove from"));
    let removed = parent
        .as_object_mut()
        .unwrap_or_else(|| panic!("{pointer} does not name an object member"))
        .remove(&key);
    assert!(removed.is_some(), "{pointer} was already absent");
}

/// Every migrated tool projects byte-for-byte what CC's zod does — key sets,
/// nested shapes, `required`, `additionalProperties`, and the `$schema`
/// envelope. Key *order* is not compared: `serde_json` preserves insertion
/// order and the carrier writes declaration order, but JSON object order is not
/// semantic on the wire.
#[test]
fn migrated_tools_project_the_official_input_schema() {
    let _environment = OracleEnvironment::pin();
    let mut report = String::new();
    for (tool_dir, schema_fn) in MIGRATED {
        let want = oracle_schema(tool_dir);
        let got = schema_fn().input_schema;
        let differences = json_differences(&got, &want);
        if differences.is_empty() {
            continue;
        }
        report.push_str(&format!("\n{tool_dir}:\n"));
        for difference in differences {
            report.push_str(&format!("  {difference}\n"));
        }
    }
    assert!(
        report.is_empty(),
        "input_schema mismatches (got vs CC):{report}"
    );
}

/// The oracle carries the draft marker, so a migrated tool ships it too — this
/// is the key `object_schema()` never emitted.
#[test]
fn migrated_tools_ship_the_draft_envelope() {
    let _environment = OracleEnvironment::pin();
    for (tool_dir, schema_fn) in MIGRATED {
        assert_eq!(
            schema_fn().input_schema["$schema"],
            serde_json::json!(crate::utils::zod::JSON_SCHEMA_DRAFT),
            "{tool_dir} lost the draft marker"
        );
    }
}

/// Each row is pinned to the tool the oracle dumped it from, so pointing a row
/// at a same-shaped neighbour's constructor cannot pass as parity.
#[test]
fn migrated_rows_name_the_tool_their_oracle_entry_came_from() {
    let _environment = OracleEnvironment::pin();
    let oracle = oracle();
    for (tool_dir, schema_fn) in MIGRATED {
        assert_eq!(
            serde_json::json!(schema_fn().name),
            oracle[tool_dir]["name"],
            "{tool_dir} row resolves to a different tool"
        );
    }
}

/// The net covers the oracle exactly: every entry is either compared or has a
/// recorded reason it cannot be, and neither list names a tool the oracle has
/// since dropped.
#[test]
fn no_oracle_entry_is_silently_dropped() {
    let oracle = oracle();
    let covered = MIGRATED
        .iter()
        .map(|(tool_dir, _)| *tool_dir)
        .chain(OUTSIDE_THE_NET.iter().map(|(tool_dir, _)| *tool_dir))
        .collect::<std::collections::BTreeSet<_>>();

    let uncovered = oracle
        .as_object()
        .expect("oracle is an object")
        .keys()
        .filter(|tool_dir| !covered.contains(tool_dir.as_str()))
        .cloned()
        .collect::<Vec<_>>();
    assert!(
        uncovered.is_empty(),
        "oracle entries outside the net: {uncovered:?}"
    );

    let stale = covered
        .iter()
        .filter(|tool_dir| oracle.get(**tool_dir).is_none())
        .collect::<Vec<_>>();
    assert!(
        stale.is_empty(),
        "net names tools the oracle dropped: {stale:?}"
    );

    let now_available = AWAITING_AN_ORACLE_ENTRY
        .iter()
        .filter(|(tool_dir, _)| oracle.get(*tool_dir).is_some())
        .map(|(tool_dir, constructors)| (*tool_dir, *constructors))
        .collect::<Vec<_>>();
    assert!(
        now_available.is_empty(),
        "the oracle now covers these — move them into MIGRATED: {now_available:?}"
    );
}

/// A gate-dependent patch cannot hide a real mismatch: it must name a tool the
/// net actually compares, point at a key the RAW oracle really has (so a patch
/// outlives neither the tool nor the property it corrects), and carry the
/// evidence for why the harness could not produce the production value.
///
/// The last assertion is the one an `Omitted` entry needs: a removal takes the
/// pointer's VALUE out of the comparison, so what keeps it under the net is
/// that the patched oracle really lost it — the port is then held to producing
/// no such property either, and a removal that silently no-opped (mis-typed
/// pointer, applier writing to a copy) would fail here instead of quietly
/// comparing the dumped node the entry said not to trust. The same assertion
/// covers `Node`: the replacement has to land where it was aimed.
#[test]
fn gate_dependent_patches_name_a_real_oracle_pointer() {
    // The projections read the schema owners' gates, and one of those
    // (`omits_run_in_background`) reads the environment.
    let _environment = OracleEnvironment::pin();
    let oracle = oracle();
    for (tool_dir, pointer, projection, reason) in GATE_DEPENDENT_ORACLE_PATCHES {
        assert!(
            MIGRATED.iter().any(|(migrated, _)| migrated == tool_dir),
            "{tool_dir} is patched but not compared"
        );
        assert!(
            !reason.is_empty(),
            "{tool_dir}{pointer} patch records no reason"
        );
        let dumped = oracle[tool_dir]["schema"].pointer(pointer);
        assert!(
            dumped.is_some(),
            "{tool_dir} oracle has no {pointer} — the patch is stale"
        );

        let patched = oracle_schema(tool_dir);
        match projection(dumped.expect("asserted above")) {
            ProductionProjection::Node(node) => assert_eq!(
                patched.pointer(pointer),
                Some(&node),
                "{tool_dir}{pointer} patch did not land"
            ),
            ProductionProjection::Omitted => assert!(
                patched.pointer(pointer).is_none(),
                "{tool_dir}{pointer} is still in the patched oracle — the removal did not land"
            ),
        }
    }
}

/// Content equality, reported as the JSON pointer of every leaf that disagrees
/// so a 30-property schema names its one bad key instead of printing both
/// documents. Objects compare key-sets and recurse, arrays compare in order,
/// numbers compare as f64 so `0` and `0.0` are one value. An empty result is
/// equality; nothing about the shape goes uncompared.
fn json_differences(got: &Value, want: &Value) -> Vec<String> {
    let mut differences = Vec::new();
    collect_differences(got, want, "", &mut differences);
    differences
}

fn collect_differences(got: &Value, want: &Value, path: &str, out: &mut Vec<String>) {
    let at = |key: &str| format!("{path}/{key}");
    match (got, want) {
        (Value::Object(got), Value::Object(want)) => {
            for (key, got_value) in got {
                match want.get(key) {
                    Some(want_value) => collect_differences(got_value, want_value, &at(key), out),
                    None => out.push(format!("{}: extra, got {got_value}", at(key))),
                }
            }
            for (key, want_value) in want {
                if !got.contains_key(key) {
                    out.push(format!("{}: missing, want {want_value}", at(key)));
                }
            }
        }
        (Value::Array(got), Value::Array(want)) if got.len() == want.len() => {
            for (index, (got_value, want_value)) in got.iter().zip(want).enumerate() {
                collect_differences(got_value, want_value, &at(&index.to_string()), out);
            }
        }
        (Value::Number(got), Value::Number(want)) if got.as_f64() == want.as_f64() => {}
        _ if got == want => {}
        _ => out.push(format!("{path}: got {got}, want {want}")),
    }
}
